spring:
  datasource:
    url: jdbc:postgresql://localhost:5000/bank_db
    username: bank_user
    password: bank_pass
  liquibase:
    change-log: classpath:db/migration/changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate
security:
  expiration-time: 3600000
jwt:
  secret: S/cZl4iy66cBZmSuXNSNHBbjSMjdP8bO2F2+EMbBW1U=
  access-token:
    expiration: 900000
  refresh-token:
    expiration: 2592000000
app:
  admin:
    username: adminUser
    password: superSecretAdminPassword
encryption:
  key: MySecretEncryptionKey123456789012