spring:
  datasource:
    url: jdbc:postgresql://localhost:5000/bank_db
    username: bank_user
    password: bank_pass
  liquibase:
    change-log: classpath:db/migration/changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate
security:
  expiration-time: 3600000